# Long Question


## 1)Write a program to create two matrix if shape(m,n) and (p,q).Check whether matrix multiplication is possible or not. If possible accept Elements of two mateices and print their product.


In [4]:
import numpy as np
m,n = 3,4
p,q = 4,3

matrix1 = []
matrix2 = []

#check if mul is possible or not

if n == p:

    #entering the data in the first matrix1
    for i in range(m):
        a=[]
        for j in range(n):
            num = int(input())
            a.append(num)
        matrix1.append(a)



    #element for matrix 2
    for i in range(p):
        a=[]
        for j in range(q):
            num = int(input())
            a.append(num)
        matrix2.append(a)
    print(matrix1)
    print(matrix2)

    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)

    mul = matrix1 @ matrix2
    print("The product of two matrix is:",mul)
else:
    print('Matrix mull is not possible')
    



[[2, 4, 6, 2], [6, 2, 7, 34], [65, 34, 65, 34]]
[[23, 54, 34], [22, 64, 34], [23, 76, 34], [65, 75, 34]]
The product of two matrix is: [[  402   970   476]
 [ 2553  3534  1666]
 [ 5948 13176  6732]]


## 2).write a program to read the contents of a text file ‘STORY.TXT’Display the frequency of words ‘the’,’is’ and ‘are’ in it.


In [12]:
f = open('stroy.txt','w')
f.write('the is are the counting is are the the is are')
f.close()

# Reading the file
f = open('stroy.txt','r')
text = f.read()
print(text)

# counting
the_count = 0
is_count = 0
are_count = 0
for i in text.split(' '):
    if i =='the':
        the_count +=1
    elif i == 'is':
        is_count +=1
    elif i == 'are':
        are_count +=1
        
print('The frequency of the :',the_count)
print('The frequency of is :',is_count)
print('The frequency of are :',are_count)



the is are the counting is are the the is are
The frequency of the : 4
The frequency of is : 3
The frequency of are : 3


## 7).write a program to read the contents of a binary file ’SALES.DAT’Print details of all product whose sales amount>25000 assumingThat each record is stored in the following format.[PID,PNAME,QTY,SALEAMOUNT].


##

In [22]:
import pickle
sales_data = [
    [1, "John Smith", 10, 1000],
    [2, "Jane Doe", 5, 52000],
    [3, "Mike Johnson", 8, 800],
    [4, "Sarah Thompson", 12, 1200],
    [5, "David Lee", 15, 122500]
]

with open('sale.dat','wb') as file:
    pickle.dump(sales_data,file)

with open('sale.dat','rb') as file:
    data = pickle.load(file)

print(data)

for i in data:
    if i[3] > 2500:
        print(i)
    


[[1, 'John Smith', 10, 1000], [2, 'Jane Doe', 5, 52000], [3, 'Mike Johnson', 8, 800], [4, 'Sarah Thompson', 12, 1200], [5, 'David Lee', 15, 122500]]
[2, 'Jane Doe', 5, 52000]
[5, 'David Lee', 15, 122500]


## 8). Write a program to accept some string from the keyboard and display its characters by index wise(both positive and negative index) .


In [58]:

str = input('Enter a string:')
print(str)
print()
print('Positive Indexing')
index = 0
for i in str:    
    print(index,':' ,i)
    index +=1
print('\t')

print('Negative Indexing')

index2 = -len(str)
for j in str:
    print(index2, ":", j)
    index2 +=1


i am tafique

Positive Indexing
0 : i
1 :  
2 : a
3 : m
4 :  
5 : t
6 : a
7 : f
8 : i
9 : q
10 : u
11 : e
	
Negative Indexing
-12 : i
-11 :  
-10 : a
-9 : m
-8 :  
-7 : t
-6 : a
-5 : f
-4 : i
-3 : q
-2 : u
-1 : e


## 9). Write a  program to reverse order of words without using slice operator.

In [61]:
s = input('Enter the text:')
word = s.split()
word.reverse()
reversed_string = ' '.join(word)
print("original text:",s)
print()
print('reversed Text:',reversed_string)





original text: this is python

reversed Text: python is this


# FOCUSSED SHORT TYPE QUESTION

## 1.write a program to count the word ‘was’ in a textfile message.txt.

In [64]:
f = open('message.txt','w')
f.write('was was was was')
f.close()

f = open('message.txt','r')
text = f.read()

print(text)
was_count = 0 
for i in text.split(' '):
    if i == 'was':
        was_count +=1

print('The frequency of was :', was_count)

was was was was
The frequency of was : 4


## 2.write a python code to create 2 matrices of shape(3,4) and print the result of element wise sum,difference,product and quotient.


In [67]:
import numpy as np
m,n = 3,4
matrix1 = []
matrix2 = []

for i in range(m):
    a=[]
    for j in range(n):
        num = int(input())
        a.append(num)
    matrix1.append(a)



    #element for matrix 2
for i in range(m):
    a=[]
    for j in range(n):
        num = int(input())
        a.append(num)
    matrix2.append(a)

print(matrix1)
print(matrix2)

matrix1 = np.array(matrix1)
matrix2 = np.array(matrix2)

print('sum:', matrix1+matrix2)
print('sub:',matrix1-matrix2)
print('mul:',matrix1 * matrix2)
print('Div:', matrix1/matrix2)




[[43, 3, 43, 75], [75, 34, 75, 34], [64, 55, 65, 43]]
[[64, 75, 34, 75], [85, 4, 6, 5], [7, 5, 75, 7]]
sum: [[107  78  77 150]
 [160  38  81  39]
 [ 71  60 140  50]]
sub: [[-21 -72   9   0]
 [-10  30  69  29]
 [ 57  50 -10  36]]
mul: [[2752  225 1462 5625]
 [6375  136  450  170]
 [ 448  275 4875  301]]
Div: [[ 0.671875    0.04        1.26470588  1.        ]
 [ 0.88235294  8.5        12.5         6.8       ]
 [ 9.14285714 11.          0.86666667  6.14285714]]


## 5)write a program to print the student whose cgpa is greater than 7.5 in a binary file student.dat.


In [71]:
import pickle
students = [
    [1, "Tapas", 8.5],
    [2, "Subrajit", 9.0],
    [3, "swapna", 7.8],
    [4, "Tafique", 8.0],
    [5, "Linden", 9.5]
]

with open('student.dat','wb') as file:
    pickle.dump(students,file)

with open('student.dat','rb') as file:
    data = pickle.load(file)

print(data)

for i in data:
    if i[2] > 7.5:
        print(i[1])

[[1, 'Tapas', 8.5], [2, 'Subrajit', 9.0], [3, 'swapna', 7.8], [4, 'Tafique', 8.0], [5, 'Linden', 9.5]]
Tapas
Subrajit
swapna
Tafique
Linden


## 7)Write a program to store the marks of five student in four different subjectin a numpy arrayprint the roll no of student having highest average.print the subject having highest average. 


## 8)write a program to accept a matrix of  order n as user input  print its Transpose also print whether or it is a symmetric matrix.


In [82]:
import numpy as np

n = 3

##entering the element of the matrix
matrix1 = []

for i in range(n):
    a=[]
    for j in range(n):
        num = int(input())
        a.append(num)
    matrix1.append(a)
matrix1 = np.array(matrix1)

transpose = matrix1.T
print(matrix1)
print()

print("Transpose of matrix:",transpose)

if np.array_equal(matrix1,transpose):
    print('symmetric')
else:
    print("Not symmetric")

[[3 2 4]
 [5 2 5]
 [7 4 8]]

Transpose of matrix: [[3 5 7]
 [2 2 4]
 [4 5 8]]
Not symmetric


## 9)write a program to create a file and store contents

In [84]:
f = open('subhrajit_gym.txt','w')
f.write('Subhrajit is going to gym and making body')
f.close()

f = open('subhrajit_gym.txt','r')
content = f.read()
print(content)

Subhrajit is going to gym and making body


## 12). write a program to create a file student csv to store name, rollno  and cgpa of n students.

In [ ]:
import csv

n = int(input("Enter the number of students: "))

# Create a list to store the student data
students = []

# Take input for each student and append to the list
for i in range(n):
    name = input("Enter the name of student {}: ".format(i+1))
    rollno = input("Enter the roll number of student {}: ".format(i+1))
    cgpa = input("Enter the CGPA of student {}: ".format(i+1))
    students.append([name, rollno, cgpa])

# Write the student data to a CSV file
with open("student.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Roll No", "CGPA"])
    writer.writerows(students)

print("Student data written to student.csv file.")

## 13). write a program to input a sentence and display each word along with its frequency.

In [95]:
str = input('Enter the string:')
print(str)

for i in str.split(' '):
    print(i,':',len(i))

subhrajit is going to gym
subhrajit : 9
is : 2
going : 5
to : 2
gym : 3


## 14). Write a program to concatenate two  numpy array.

In [94]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate the two arrays
c = np.concatenate([a, b])

# Print the concatenated array
print(c)

[1 2 3 4 5 6]
